-- ============================================================================
-- Payroll 2.0 — Async payslip generation jobs (migration 019)
--
-- Payslip PDFs are generated by a BullMQ fan-out (one job per employee) instead
-- of synchronously in the HTTP request. These two tables are the DB source of
-- truth for progress + resume (the queue can drop/replay; the DB cannot):
--
--   pay_payslip_jobs       — one header row per run (counts + overall status).
--   pay_payslip_job_items  — one row per employee (claim state for idempotency,
--                            attempts, last error). "Pending" = status <> 'done';
--                            the "Complete pending" action re-enqueues these.
--
-- Tenant isolation = RLS (FORCE'd) + explicit tenant_id filters, matching the
-- rest of the module.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid()

CREATE TABLE IF NOT EXISTS pay_payslip_jobs (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     uuid NOT NULL,
  run_id        uuid NOT NULL REFERENCES pay_runs (id) ON DELETE CASCADE,
  status        text NOT NULL DEFAULT 'queued'
                  CHECK (status IN ('queued', 'running', 'completed', 'completed_with_errors', 'failed')),
  total         integer NOT NULL DEFAULT 0,
  succeeded     integer NOT NULL DEFAULT 0,
  failed        integer NOT NULL DEFAULT 0,
  requested_by  uuid,
  started_at    timestamptz,
  finished_at   timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- One header per run (regenerate reuses the same row).
CREATE UNIQUE INDEX IF NOT EXISTS uq_pay_payslip_jobs_run ON pay_payslip_jobs (run_id);

CREATE TABLE IF NOT EXISTS pay_payslip_job_items (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     uuid NOT NULL,
  run_id        uuid NOT NULL REFERENCES pay_runs (id) ON DELETE CASCADE,
  employee_id   uuid NOT NULL,
  status        text NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'processing', 'done', 'failed')),
  attempts      integer NOT NULL DEFAULT 0,
  error         text,
  payslip_id    uuid,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pay_payslip_job_items_run_emp ON pay_payslip_job_items (run_id, employee_id);
CREATE INDEX IF NOT EXISTS ix_pay_payslip_job_items_run ON pay_payslip_job_items (tenant_id, run_id, status);
-- Janitor lookup for stale 'processing' rows.
CREATE INDEX IF NOT EXISTS ix_pay_payslip_job_items_stale ON pay_payslip_job_items (status, updated_at);

-- ─── Row-Level Security ─────────────────────────────────────────────────────
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['pay_payslip_jobs', 'pay_payslip_job_items']
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', t);
    EXECUTE format($f$
      CREATE POLICY tenant_isolation ON %I
        USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.current_tenant_id', true)::uuid)
    $f$, t);
  END LOOP;
END $$;
