export enum AIFeature {
    PROPOSAL_GENERATION = 'PROPOSAL_GENERATION',
    MAIL_ASSISTANT = 'MAIL_ASSISTANT',
    BID_IQ_ANALYSIS = 'BID_IQ_ANALYSIS',
    DOCUMENT_SUMMARY = 'DOCUMENT_SUMMARY',
    TICKET_ANALYSIS = 'TICKET_ANALYSIS',
    BUG_ANALYSIS = 'BUG_ANALYSIS',
    SPRINT_SUMMARY = 'SPRINT_SUMMARY',
    /** Zai drafting a QA Playbook recommendation from a one-line brief. */
    PLAYBOOK_DRAFT = 'PLAYBOOK_DRAFT'
}
