export const PREDEFINED_SECTIONS = ["WORK", "HRMS", "ADMIN", "FINANCE", "HOME"];

export const PREDEFINED_MODULES = [
  { section: "WORK", module: "Tickets" },
  { section: "WORK", module: "Projects" },
  { section: "WORK", module: "TimeTracking" },
  { section: "WORK", module: "DailyUpdates" },
  { section: "WORK", module: "DocumentHub" },
  { section: "WORK", module: "Proposals" },
  { section: "WORK", module: "Squad" },
  { section: "WORK", module: "Escalations" },
  { section: "WORK", module: "LeadsManagement" },
  { section: "WORK", module: "BidIQ" },
  { section: "WORK", module: "QaWorkspace" },
  { section: "WORK", module: "ApiHub" },
  { section: "HRMS", module: "Leaves" },
  { section: "HRMS", module: "Onboarding" },
  { section: "HRMS", module: "Attendance" },
  { section: "HRMS", module: "MyProfile" },
  { section: "HRMS", module: "PerformanceReport" },
  { section: "ADMIN", module: "ClientsV2" },
  { section: "ADMIN", module: "GeneralSettings" },
  { section: "ADMIN", module: "Members" },
  { section: "ADMIN", module: "RoleAndPermissions" },
  { section: "ADMIN", module: "OrgStructure" },
  { section: "HOME", module: "Dashboard" },
  { section: "HOME", module: "Integrations" },
  { section: "HOME", module: "Skills" },
  { section: "HOME", module: "Messages" },
  { section: "HOME", module: "Bookmarks" },
  { section: "HOME", module: "Hotspot" },
  { section: "ADMIN", module: "Auth" },
  { section: "FINANCE", module: "Accounts" },
  { section: "FINANCE", module: "Invoices" },
  { section: "FINANCE", module: "ReimbursementV2" },
  { section: "FINANCE", module: "PayrollV2" },
];

export const PREDEFINED_PAGES = [
  { module: "Tickets", page: "Plans" },
  { module: "Tickets", page: "TicketList" },
  { module: "Tickets", page: "Buckets" },
  { module: "Tickets", page: "Reports" },
  { module: "Tickets", page: "Settings" },
  { module: "Tickets", page: "Trash" },
  { module: "Tickets", page: "Archive" },
  { module: "QaWorkspace", page: "QaScopeList" },
  { module: "QaWorkspace", page: "QaCaseList" },
  { module: "QaWorkspace", page: "QaSuiteList" },
  { module: "QaWorkspace", page: "QaRunList" },
  { module: "QaWorkspace", page: "BugList" },
  { module: "QaWorkspace", page: "QaSubmissionList" },
  { module: "QaWorkspace", page: "QaApprovals" },
  { module: "QaWorkspace", page: "QaAnalytics" },
  { module: "QaWorkspace", page: "QaSettings" },
  { module: "DocumentHub", page: "DocumentHubList" },
  { module: "DocumentHub", page: "DocumentDetail" },
  { module: "LeadsManagement", page: "LeadsList" },
  { module: "LeadsManagement", page: "LeadDetail" },
  { module: "LeadsManagement", page: "LeadSettings" },
  { module: "LeadsManagement", page: "LeadsTrash" },
  { module: "BidIQ", page: "BidIQDashboard" },
  { module: "BidIQ", page: "BidIQSettings" },
  { module: "Proposals", page: "ProposalList" },
  { module: "Proposals", page: "ProposalBuilder" },
  { module: "Squad", page: "SquadView" },
  { module: "Escalations", page: "EscalationList" },
  { module: "Escalations", page: "EscalationSettings" },
  { module: "Escalations", page: "EscalationsTrash" },
  { module: "DailyUpdates", page: "DailyUpdatesSubmit" },
  { module: "TimeTracking", page: "TimeTrackingMy" },
  { module: "TimeTracking", page: "TimeTrackingTeam" },
  { module: "OrgStructure", page: "OrgStructureOverview" },
  { module: "OrgStructure", page: "OrgStructureGrades" },
  { module: "OrgStructure", page: "OrgStructureEmploymentTypes" },
  { module: "OrgStructure", page: "OrgStructureDepartments" },
  { module: "OrgStructure", page: "OrgStructureSubDepartments" },
  { module: "OrgStructure", page: "OrgStructurePositions" },
  { module: "Leaves", page: "LeaveRequests" },
  { module: "Leaves", page: "LeaveApprovals" },
  { module: "Leaves", page: "LeaveAdjustments" },
  { module: "Leaves", page: "LeaveTypes" },
  { module: "Leaves", page: "LeavePolicies" },
  { module: "Leaves", page: "LeaveHolidays" },
  { module: "Leaves", page: "LeaveAccrual" },
  { module: "Onboarding", page: "OnboardingInvites" },
  { module: "Onboarding", page: "OnboardingEmployees" },
  { module: "Onboarding", page: "OnboardingDocumentTypes" },
  { module: "Attendance", page: "AttendanceDashboard" },
  { module: "Attendance", page: "AttendanceRecords" },
  { module: "MyProfile", page: "MyProfile" },
  { module: "PerformanceReport", page: "PerformanceReport" },
  { module: "ClientsV2", page: "ClientList" },
  { module: "ClientsV2", page: "ClientDetail" },
  { module: "GeneralSettings", page: "GeneralSettingsView" },
  { module: "Members", page: "MemberList" },
  { module: "RoleAndPermissions", page: "RoleList" },
  { module: "Hotspot", page: "Circulation" },
  { module: "Hotspot", page: "Blogs" },
  { module: "Hotspot", page: "Openings" },
  { module: "Auth", page: "Login" },
  { module: "Accounts", page: "AccountsDashboard" },
  { module: "Accounts", page: "AccountsSettings" },
  { module: "Invoices", page: "InvoiceList" },
  { module: "Invoices", page: "InvoiceDetail" },
  { module: "Invoices", page: "InvoiceCustomerList" },
  { module: "Invoices", page: "InvoiceSettingsView" },
  { module: "Invoices", page: "InvoiceTemplateList" },
  { module: "Invoices", page: "InvoiceTrashView" },
  { module: "ReimbursementV2", page: "ReimbursementDashboard" },
  { module: "ReimbursementV2", page: "ReimbursementMyClaims" },
  { module: "ReimbursementV2", page: "ReimbursementAdvances" },
  { module: "ReimbursementV2", page: "ReimbursementApprovals" },
  { module: "ReimbursementV2", page: "ReimbursementFinance" },
  { module: "ReimbursementV2", page: "ReimbursementCategories" },
  { module: "ReimbursementV2", page: "ReimbursementPolicies" },
  { module: "ReimbursementV2", page: "ReimbursementBudgets" },
  { module: "ReimbursementV2", page: "ReimbursementSettings" },
  { module: "PayrollV2", page: "PayrollGeneralSettings" },
  { module: "PayrollV2", page: "PayrollSalaryComponents" },
  { module: "PayrollV2", page: "PayrollSalaryStructures" },
  { module: "PayrollV2", page: "PayrollPaySchedulesAndGroups" },
  { module: "PayrollV2", page: "PayrollStatutory" },
  { module: "PayrollV2", page: "PayrollProfessionalTaxAndLwf" },
  { module: "PayrollV2", page: "PayrollApprovalWorkflows" },
  { module: "PayrollV2", page: "PayrollPayslipAndBank" },
  { module: "PayrollV2", page: "PayrollEmployeePaySetup" },
  { module: "PayrollV2", page: "PayrollRunPayroll" },
  { module: "PayrollV2", page: "PayrollReports" },
  { module: "PayrollV2", page: "PayrollMyPayslips" },
];

export const PREDEFINED_ACTIONS = [
  "create", "update", "delete", "archive", "restore", "permanent_delete", "status_change",
  "move", "convert", "verify", "reopen", "bulk_update_status", "bulk_archive", "bulk_unarchive",
  "bulk_delete", "bulk_restore", "bulk_permanent_delete", "bulk_move", "bulk_convert", "start",
  "complete", "bulk_assign", "bulk_unassign", "bulk_resolve", "generate_ai", "empty_trash",
  "auto_purge", "reorder", "share", "unshare", "download", "email_sent", "login", "logout",
  "apply", "approve", "reject", "cancel", "run", "revoke", "activate", "submit"
];

export const PREDEFINED_ENTITY_TYPES = [
  "ticket", "bug", "bug_folder", "bug_sheet", "bug_severity_option", "bug_type_option",
  "project", "project_member", "release_plan", "sprint_ai_narrative", "bucket", "bucket_member",
  "workflow_template", "dropdown_option", "document_hub", "document_tree_node", "document",
  "document_history_entry", "lead", "lead_status", "lead_action_option", "proposal", "squad",
  "escalation", "escalation_category", "escalation_priority", "escalation_status", "daily_update",
  "time_entry", "org_grade", "org_employment_type", "org_department", "org_sub_department", "org_position", "client", "client_contact", "client_document", "client_allocation",
  "tenant_settings", "user", "role", "permission", "role_permission", "user_role",
  "invoice", "account_transaction", "invoice_payment",
  "invoice_template", "invoice_customer", "invoice_settings_profile", "session",
  "leave_request", "leave_adjustment", "leave_type", "leave_policy",
  "qa_submission", "qa_parent_case", "qa_case", "qa_suite", "qa_run", "qa_scope", "qa_settings", "qa_analytics", "qa_module",
  "leave_holiday", "leave_accrual_run", "leave_settings",
  "employee", "onboarding_invite", "onboarding_document_type",
  "attendance_record", "performance_report",
  "circulation", "blog", "opening"
];

export const HIDDEN_MODULES = [
  "InvoiceCustomers", "InvoiceSettings", "InvoiceTemplates", "InvoiceTrash", "Reimbursement"
];

export const MODULE_REWRITES: Record<string, string> = {
  "InvoiceCustomers": "Invoices",
  "InvoiceSettings": "Invoices",
  "InvoiceTemplates": "Invoices",
  "InvoiceTrash": "Invoices",
  "Sprints": "Tickets",
  "Buckets": "Tickets",
  "TicketSettings": "Tickets",
  "Trash": "Tickets",
  "Archived": "Tickets",
  "BugList": "QaWorkspace",
  "QA": "QaWorkspace",
  "Leads": "LeadsManagement"
};

export const SECTION_REWRITES: Record<string, string> = {
  "OrgStructure": "ADMIN"
};

export const PAGE_REWRITES: Record<string, Record<string, string>> = {
  "QaWorkspace": {
    "TestCases": "QaCaseList",
    "TestCaseDetails": "QaCaseList",
    "QaCaseDetail": "QaCaseList",
    "QaParentCase": "QaCaseList",
    "TestRuns": "QaRunList",
    "TestRunExecution": "QaRunList",
    "QaRunDetail": "QaRunList",
    "TestSuites": "QaSuiteList",
    "QaSuiteDetail": "QaSuiteList",
    "TestScope": "QaScopeList",
    "CreateTestScope": "QaScopeList",
    "EditTestScope": "QaScopeList",
    "QaScopeDetail": "QaScopeList",
    "QaSubmissions": "QaSubmissionList",
    "QaSubmissionForm": "QaSubmissionList",
    "QaSubmissionDetail": "QaSubmissionList",
    "BugFolderList": "BugList",
    "BugSheetList": "BugList",
    "BugTrash": "BugList",
    "BugSettings": "QaSettings"
  },
  "Tickets": {
    "TicketDetail": "TicketList"
  },
  "TimeTracking": {
    "TicketDetail": "TimeTrackingDetails"
  }
};
